### ISSUE TITLE
AGS - unable to load main.js

### ISSUE THREAD

**Issue by gnussbaum1967** [ImRayy/ags-dots#1]
Hi Ray,

I installed ags following your directions.  When I type ags I get the following error message:

![image](https://github.com/user-attachments/assets/91090c6e-9227-491a-b55d-43f657930566)

Any idea where main.js is or how it is created?

**Comment by ImRayy** [comment]
> Hi Ray,
> 
> I installed ags following your directions. When I type ags I get the following error message:
> 
> ![image](https://private-user-images.githubusercontent.com/147539736/383300250-91090c6e-9227-491a-b55d-43f657930566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjc0MjUsIm5iZiI6MTczMTEyNzEyNSwicGF0aCI6Ii8xNDc1Mzk3MzYvMzgzMzAwMjUwLTkxMDkwYzZlLTkyMjctNDkxYS1iNTVkLTQzZjY1NzkzMDU2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNDM4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTcyMDEyNzljMmQ5ZGQyZTVmYjU4YjQ4ZDA5MzcyZGQyOGU5MmM2N2NlMGZhYjNiMWVmOGRmM2NjM2FjMThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4SlWs6FqeOkiDoR3CUvUrL1uYVc3LXt79mY3Y7vYgWs)
> 
> Any idea where main.js is or how it is created?

Hey [gnussbaum1967](https://github.com/gnussbaum1967), sorry for the late reply! 😓 

It seems your files aren’t building, which is why you’re seeing `Unable to load file from:///tmp/ags/main.js`. Make sure you have [Bun](https://bun.sh/) and other dependencies installed properly.
