### ISSUE TITLE
Question about cpu module-vars

### ISSUE THREAD

**Issue by omnigenous** [ImRayy/ags-dots#2]
https://github.com/ImRayy/ags-dots/blob/master/module-vars/cpu.ts

I can't figure out how to get this part to work:

```
Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
```

I'm using ags v2 with astal. Couldn't find `libtop` in arch repos or aur.

**Comment by ImRayy** [comment]
> ```
> Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
> ```

Install `libgtop`, also sorry for late reply :disappointed: I realized I haven't been receiving email notifications

**Comment by omnigenous** [comment]
Thank you

**Comment by ImRayy** [comment]
You're welcome ;)
